# Generated by Django 4.0.3 on 2023-10-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
